apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: ecommerce
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: mongo-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-0.mongodb-service.ecommerce.svc.cluster.local"
        ports:
        - containerPort: 8081
